### ISSUE TITLE
In memory tests support

### ISSUE THREAD

**Issue by vforv** [hemerajs/hapi-hemera#8]
Hello,

it would be good if someone can create PR to add in memory tests for hapi hemera.

**Comment by StarpTech** [comment]
Sry, for the late response. This can be easily archived by hemera-testsuite package and hapi's inject functionality the only task to do is to allow when passing the Nats instance as an option to this plugin. Would you like to create a PR?

**Comment by StarpTech** [comment]
Closed, due to inactivity.
