### ISSUE TITLE
Testing with real nats server error

### ISSUE THREAD

**Issue by vforv** [hemerajs/hapi-hemera#9]
I am not sure if this error is related to hapi-hemera, but I think it is. I am getting this error:

> Test script errors:
> 
> Server exited with bad code, already running? (1 / null)
>       at emitTwo (events.js:106:13)
>       at ChildProcess.emit (events.js:191:7)
>       at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> 
> There were 1 test script error(s).

Here is the simplified code:

https://github.com/vforv/hemera-testsuite-error

**Comment by StarpTech** [comment]
Do you have still the issue?

**Comment by vforv** [comment]
No, everything is okay :)
